apiVersion: apps/v1
kind: Deployment

metadata:
  name: prometheus
  namespace: monitoring

spec:
  replicas: 1

  selector:
    matchLabels:
      app: prometheus

  template:
    metadata:
      labels:
        app: prometheus

    spec:
      containers:
        - name: prometheus
          image: prom/prometheus

          args:
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus"

          ports:
            - containerPort: 9090

          readinessProbe:
            httpGet:
              path: /-/ready
              port: 9090
            initialDelaySeconds: 10
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /-/healthy
              port: 9090
            initialDelaySeconds: 30
            periodSeconds: 15

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"

            limits:
              cpu: "500m"
              memory: "512Mi"

          volumeMounts:
            - name: prometheus-config-volume
              mountPath: /etc/prometheus

            - name: prometheus-storage
              mountPath: /prometheus

      volumes:
        - name: prometheus-config-volume
          configMap:
            name: prometheus-config

        - name: prometheus-storage
          persistentVolumeClaim:
            claimName: prometheus-pvc