apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: worldops-ingress
  namespace: worldops

  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.middlewares: worldops-strip-api@kubernetescrd

spec:
  ingressClassName: traefik

  tls:
    - hosts:
        - worldops2026.duckdns.org
      secretName: worldops-tls

  rules:
    - host: worldops2026.duckdns.org
      http:
        paths:

          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80

          - path: /api
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 8000